[pytest]
testpaths = tests
python_files = test_*.py
addopts = --basetemp=.pytest_tmp
cache_dir = .pytest_cache
norecursedirs =
    .pytest_cache
    .pytest_tmp
    __pycache__
    pytest-cache-files-*
    data/pytest_tmp2
    data/test_tmp
