[pytest]
testpaths = tests
python_files = test_*.py
addopts = --basetemp=_pytest_tmp -p no:cacheprovider
cache_dir = _pytest_cache
norecursedirs =
    _pytest_cache
    _pytest_tmp
    _tmp
    __pycache__
    pytest-cache-files-*
    data/pytest_tmp2
    data/test_tmp
